Importing Packages and creating dataframe

In [36]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
pd.set_option('display.float_format', lambda x: '%.2f' % x)
warnings.filterwarnings('ignore')
fifa=pd.read_excel("FIFA.xlsx")
df = fifa.copy()

check how many rows and columns are in the dataset

In [8]:
df.shape

(17981, 74)

Describe the dataset to get the stats of each column

In [6]:
df.describe()

,Unnamed: 0,Age,Overall,Potential,Special,CAM,CB,CDM,CF,CM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
count,17981.000000,17981.000000,17981.000000,17981.000000,17981.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,...,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000
mean,8990.000000,25.144541,66.247984,71.190813,1594.095100,59.251755,55.550464,56.865283,59.030028,58.506833,...,56.979689,55.550464,58.506833,56.865283,59.030028,60.057736,58.204050,59.359265,57.698721,58.204050
std,5190.811931,4.614272,6.987965,6.102199,272.151435,9.880164,12.192579,10.310178,9.926988,8.888040,...,9.791627,12.192579,8.888040,10.310178,9.926988,9.349180,9.181392,9.978084,9.142825,9.181392
min,0.000000,16.000000,46.000000,46.000000,728.000000,27.000000,25.000000,26.000000,27.000000,30.000000,...,30.000000,25.000000,30.000000,26.000000,27.000000,28.000000,31.000000,26.000000,31.000000,31.000000
25%,4495.000000,21.000000,62.000000,67.000000,1449.000000,53.000000,45.000000,49.000000,53.000000,53.000000,...,50.000000,45.000000,53.000000,49.000000,53.000000,54.000000,52.000000,53.000000,51.000000,52.000000
50%,8990.000000,25.000000,66.000000,71.000000,1633.000000,60.000000,57.000000,58.000000,60.000000,59.000000,...,58.000000,57.000000,59.000000,58.000000,60.000000,61.000000,59.000000,60.000000,58.000000,59.000000
75%,13485.000000,28.000000,71.000000,75.000000,1786.000000,66.000000,65.000000,65.000000,66.000000,65.000000,...,64.000000,65.000000,65.000000,65.000000,66.000000,67.000000,65.000000,66.000000,64.000000,65.000000
max,17980.000000,47.000000,94.000000,94.000000,2291.000000,92.000000,87.000000,85.000000,92.000000,87.000000,...,84.000000,87.000000,87.000000,85.000000,92.000000,90.000000,92.000000,91.000000,84.000000,92.000000

See what the data types are for each column

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 74 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17981 non-null  int64
 1   Name                 17981 non-null  object
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  object
 4   Nationality          17981 non-null  object
 5   Flag                 17981 non-null  object
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  object
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  object
 11  Wage                 17981 non-null  object
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  object
 14  Aggression           17981 non-null  object
 15  Agility              17981 non-null  object
 16  Balance              17981 non-null  object
 17  Ball control         17981 non-null  object
 18  Composure            17981 non-null  object
 19  Crossing             17981 non-null  object
 20  Curve                17981 non-null  object
 21  Dribbling            17981 non-null  object
 22  Finishing            17981 non-null  object
 23  Free kick accuracy   17981 non-null  object
 24  GK diving            17981 non-null  object
 25  GK handling          17981 non-null  object
 26  GK kicking           17981 non-null  object
 27  GK positioning       17981 non-null  object
 28  GK reflexes          17981 non-null  object
 29  Heading accuracy     17981 non-null  object
 30  Interceptions        17981 non-null  object
 31  Jumping              17981 non-null  object
 32  Long passing         17981 non-null  object
 33  Long shots           17981 non-null  object
 34  Marking              17981 non-null  object
 35  Penalties            17981 non-null  object
 36  Positioning          17981 non-null  object
 37  Reactions            17981 non-null  object
 38  Short passing        17981 non-null  object
 39  Shot power           17981 non-null  object
 40  Sliding tackle       17981 non-null  object
 41  Sprint speed         17981 non-null  object
 42  Stamina              17981 non-null  object
 43  Standing tackle      17981 non-null  object
 44  Strength             17981 non-null  object
 45  Vision               17981 non-null  object
 46  Volleys              17981 non-null  object
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  LAM                  15952 non-null  float64
 53  LB                   15952 non-null  float64
 54  LCB                  15952 non-null  float64
 55  LCM                  15952 non-null  float64
 56  LDM                  15952 non-null  float64
 57  LF                   15952 non-null  float64
 58  LM                   15952 non-null  float64
 59  LS                   15952 non-null  float64
 60  LW                   15952 non-null  float64
 61  LWB                  15952 non-null  float64
 62  Preferred Positions  17981 non-null  object
 63  RAM                  15952 non-null  float64
 64  RB                   15952 non-null  float64
 65  RCB                  15952 non-null  float64
 66  RCM                  15952 non-null  float64
 67  RDM                  15952 non-null  float64
 68  RF                   15952 non-null  float64
 69  RM                   15952 non-null  float64
 70  RS                   15952 non-null  float64
 71  RW                   15952 non-null  float64
 72  RWB                  15952 non-null  float64
 73  ST                   15952 non-null  float64
dtypes: float64(26), int64(5), object(43)
memory usage: 10.2+ MB

Create new Position column to hold other prefered positions if player has more than one, and show that the column was created.

In [37]:
df['Position'] = df['Preferred Positions'].apply(lambda x: x[:3])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 75 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17981 non-null  int64
 1   Name                 17981 non-null  object
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  object
 4   Nationality          17981 non-null  object
 5   Flag                 17981 non-null  object
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  object
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  object
 11  Wage                 17981 non-null  object
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  object
 14  Aggression           17981 non-null  object
 15  Agility              17981 non-null  object
 16  Balance              17981 non-null  object
 17  Ball control         17981 non-null  object
 18  Composure            17981 non-null  object
 19  Crossing             17981 non-null  object
 20  Curve                17981 non-null  object
 21  Dribbling            17981 non-null  object
 22  Finishing            17981 non-null  object
 23  Free kick accuracy   17981 non-null  object
 24  GK diving            17981 non-null  object
 25  GK handling          17981 non-null  object
 26  GK kicking           17981 non-null  object
 27  GK positioning       17981 non-null  object
 28  GK reflexes          17981 non-null  object
 29  Heading accuracy     17981 non-null  object
 30  Interceptions        17981 non-null  object
 31  Jumping              17981 non-null  object
 32  Long passing         17981 non-null  object
 33  Long shots           17981 non-null  object
 34  Marking              17981 non-null  object
 35  Penalties            17981 non-null  object
 36  Positioning          17981 non-null  object
 37  Reactions            17981 non-null  object
 38  Short passing        17981 non-null  object
 39  Shot power           17981 non-null  object
 40  Sliding tackle       17981 non-null  object
 41  Sprint speed         17981 non-null  object
 42  Stamina              17981 non-null  object
 43  Standing tackle      17981 non-null  object
 44  Strength             17981 non-null  object
 45  Vision               17981 non-null  object
 46  Volleys              17981 non-null  object
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  LAM                  15952 non-null  float64
 53  LB                   15952 non-null  float64
 54  LCB                  15952 non-null  float64
 55  LCM                  15952 non-null  float64
 56  LDM                  15952 non-null  float64
 57  LF                   15952 non-null  float64
 58  LM                   15952 non-null  float64
 59  LS                   15952 non-null  float64
 60  LW                   15952 non-null  float64
 61  LWB                  15952 non-null  float64
 62  Preferred Positions  17981 non-null  object
 63  RAM                  15952 non-null  float64
 64  RB                   15952 non-null  float64
 65  RCB                  15952 non-null  float64
 66  RCM                  15952 non-null  float64
 67  RDM                  15952 non-null  float64
 68  RF                   15952 non-null  float64
 69  RM                   15952 non-null  float64
 70  RS                   15952 non-null  float64
 71  RW                   15952 non-null  float64
 72  RWB                  15952 non-null  float64
 73  ST                   15952 non-null  float64
 74  Position             17981 non-null  object
dtypes: float64(26), int64(5), object(44)
memory usage: 10.3+ MB

## Describing the dataset to get an overview.

In [13]:
df.describe()

,Unnamed: 0,Age,Overall,Potential,Special,CAM,CB,CDM,CF,CM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
count,17981.000000,17981.000000,17981.000000,17981.000000,17981.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,...,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000
mean,8990.000000,25.144541,66.247984,71.190813,1594.095100,59.251755,55.550464,56.865283,59.030028,58.506833,...,56.979689,55.550464,58.506833,56.865283,59.030028,60.057736,58.204050,59.359265,57.698721,58.204050
std,5190.811931,4.614272,6.987965,6.102199,272.151435,9.880164,12.192579,10.310178,9.926988,8.888040,...,9.791627,12.192579,8.888040,10.310178,9.926988,9.349180,9.181392,9.978084,9.142825,9.181392
min,0.000000,16.000000,46.000000,46.000000,728.000000,27.000000,25.000000,26.000000,27.000000,30.000000,...,30.000000,25.000000,30.000000,26.000000,27.000000,28.000000,31.000000,26.000000,31.000000,31.000000
25%,4495.000000,21.000000,62.000000,67.000000,1449.000000,53.000000,45.000000,49.000000,53.000000,53.000000,...,50.000000,45.000000,53.000000,49.000000,53.000000,54.000000,52.000000,53.000000,51.000000,52.000000
50%,8990.000000,25.000000,66.000000,71.000000,1633.000000,60.000000,57.000000,58.000000,60.000000,59.000000,...,58.000000,57.000000,59.000000,58.000000,60.000000,61.000000,59.000000,60.000000,58.000000,59.000000
75%,13485.000000,28.000000,71.000000,75.000000,1786.000000,66.000000,65.000000,65.000000,66.000000,65.000000,...,64.000000,65.000000,65.000000,65.000000,66.000000,67.000000,65.000000,66.000000,64.000000,65.000000
max,17980.000000,47.000000,94.000000,94.000000,2291.000000,92.000000,87.000000,85.000000,92.000000,87.000000,...,84.000000,87.000000,87.000000,85.000000,92.000000,90.000000,92.000000,91.000000,84.000000,92.000000

# Convert value and wage to numerical types

In [64]:
columns_to_numerical = ['Acceleration', 'Aggression', 'Agility', 'Balance', 'Ball Control', 'Composure', 'Crossing', 'Curve',
                       'Dribbling', 'Finishing', 'Free kick accuracy', 'GK diving', 'GK handling', 'GK kicking', 'GK positioning',
                       'GK reflexes', 'Heading accuracy', 'Interceptions', 'Jumping', 'Long passing', 'Long shots', 'Marking', 'Penalties', 'Positioning',
                       'Reactions', 'Short passing', 'Shot power', 'Sliding tackle', 'Sprint speed', 'Stamina', 'Standing tackle', 'Strength', 'Vision', 'Volleys'
                       ]

#df['Value'] = df['Value'].replace({'K': '*1e3', 'M': '*1e6'}, regex=True).map(pd.eval).astype(int)
#df['Wage'] = df['Wage'].replace({'K': '*1e3', 'M': '*1e6'}, regex=True).map(pd.eval).astype(int)

for col in columns_to_numerical:
    df[col] = df[col].map(pd.eval).astype(int)

KeyError: 'Ball Control'

In [39]:
df.describe()

,Unnamed: 0,Age,Overall,Potential,Value,Wage,Special,CAM,CB,CDM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
count,17981.00,17981.00,17981.00,17981.00,17981.00,17981.00,17981.00,15952.00,15952.00,15952.00,...,15952.00,15952.00,15952.00,15952.00,15952.00,15952.00,15952.00,15952.00,15952.00,15952.00
mean,8990.00,25.14,66.25,71.19,2385389.58,11546.97,1594.10,59.25,55.55,56.87,...,56.98,55.55,58.51,56.87,59.03,60.06,58.20,59.36,57.70,58.20
std,5190.81,4.61,6.99,6.10,5353969.97,23080.00,272.15,9.88,12.19,10.31,...,9.79,12.19,8.89,10.31,9.93,9.35,9.18,9.98,9.14,9.18
min,0.00,16.00,46.00,46.00,0.00,0.00,728.00,27.00,25.00,26.00,...,30.00,25.00,30.00,26.00,27.00,28.00,31.00,26.00,31.00,31.00
25%,4495.00,21.00,62.00,67.00,300000.00,2000.00,1449.00,53.00,45.00,49.00,...,50.00,45.00,53.00,49.00,53.00,54.00,52.00,53.00,51.00,52.00
50%,8990.00,25.00,66.00,71.00,675000.00,4000.00,1633.00,60.00,57.00,58.00,...,58.00,57.00,59.00,58.00,60.00,61.00,59.00,60.00,58.00,59.00
75%,13485.00,28.00,71.00,75.00,2100000.00,12000.00,1786.00,66.00,65.00,65.00,...,64.00,65.00,65.00,65.00,66.00,67.00,65.00,66.00,64.00,65.00
max,17980.00,47.00,94.00,94.00,123000000.00,565000.00,2291.00,92.00,87.00,85.00,...,84.00,87.00,87.00,85.00,92.00,90.00,92.00,91.00,84.00,92.00

For both Value and Wage, the mean is much larger than the median, which shows a right skewed distribution.
So there are a smaller amount of players that have a significantly higher value and wage the the majority of players.

In [40]:
df.isnull().sum()

Unnamed: 0        0
Name              0
Age               0
Photo             0
Nationality       0
               ...
RS             2029
RW             2029
RWB            2029
ST             2029
Position          0
Length: 75, dtype: int64

In [53]:
df[(df['Club'] == 'Real Madrid CF')].head()

,Unnamed: 0,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST,Position
0,0,Cristiano Ronaldo,32,https://cdn.sofifa.org/48/18/players/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,53.00,82.00,62.00,91.00,89.00,92.00,91.00,66.00,92.00,ST
8,8,T. Kroos,27,https://cdn.sofifa.org/48/18/players/182521.png,Germany,https://cdn.sofifa.org/flags/21.png,90,90,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,72.00,87.00,82.00,81.00,81.00,77.00,80.00,78.00,77.00,CDM
10,10,Sergio Ramos,31,https://cdn.sofifa.org/48/18/players/155862.png,Spain,https://cdn.sofifa.org/flags/45.png,90,90,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,87.00,74.00,83.00,70.00,71.00,72.00,69.00,81.00,72.00,CB
14,14,L. ModriÃ„â€¡,31,https://cdn.sofifa.org/48/18/players/177003.png,Croatia,https://cdn.sofifa.org/flags/10.png,89,89,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,72.00,86.00,80.00,83.00,84.00,76.00,83.00,80.00,76.00,CDM
15,15,G. Bale,27,https://cdn.sofifa.org/48/18/players/173731.png,Wales,https://cdn.sofifa.org/flags/50.png,89,89,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,67.00,81.00,71.00,87.00,87.00,87.00,87.00,74.00,87.00,RW

In [51]:
df['Club'].unique()

array(['Real Madrid CF', 'FC Barcelona', 'Paris Saint-Germain',
       'FC Bayern Munich', 'Manchester United', 'Chelsea', 'Juventus',
       'Manchester City', 'Arsenal', 'AtlÃƒÂ©tico Madrid',
       'Borussia Dortmund', 'Milan', 'Tottenham Hotspur', 'Napoli',
       'Inter', 'Liverpool', 'Roma', 'BeÃ…Å¸iktaÃ…Å¸ JK', 'AS Monaco',
       'Bayer 04 Leverkusen', 'AS Saint-Ãƒâ€°tienne',
       'Athletic Club de Bilbao', '1. FC KÃƒÂ¶ln', 'Villarreal CF',
       'FC Schalke 04', 'Olympique de Marseille', 'Atalanta',
       'RB Leipzig', 'Real Sociedad', 'Torino', 'Sporting CP',
       'Leicester City', 'Southampton', 'FC Porto', 'UD Las Palmas',
       'Olympique Lyonnais', 'Lazio', 'Genoa', 'Everton',
       'RC Celta de Vigo', 'Valencia CF', nan, 'Sevilla FC', 'Toronto FC',
       'Borussia MÃƒÂ¶nchengladbach', 'SL Benfica', 'RCD Espanyol',
       'OGC Nice', 'Spartak Moscow', 'Swansea City', 'Sassuolo',
       'TSG 1899 Hoffenheim', 'Stoke City', 'Shakhtar Donetsk',
       'West Ham United', 'SV Werder Bremen', 'Watford', 'Galatasaray SK',
       'Lokomotiv Moscow', 'Zenit St. Petersburg', 'Bournemouth',
       'Sampdoria', 'Antalyaspor', 'Girondins de Bordeaux',
       'VfL Wolfsburg', 'New York City Football Club',
       'Hertha BSC Berlin', 'SD Eibar', 'Ajax',
       'RC Deportivo de La CoruÃƒÂ±a', 'Crystal Palace',
       'West Bromwich Albion', 'CSKA Moscow', 'Eintracht Frankfurt',
       'Real Betis BalompiÃƒÂ©', 'FenerbahÃƒÂ§e SK', 'Fiorentina', 'Burnley',
       'Tigres U.A.N.L.', 'San Lorenzo de Almagro',
       'Chicago Fire Soccer Club', 'Feyenoord', 'FC Krasnodar',
       'Angers SCO', 'U.N.A.M.', 'Montreal Impact', 'Chievo Verona',
       'LA Galaxy', 'Vissel Kobe', 'Bologna', 'LOSC Lille',
       'Orlando City Soccer Club', 'Atlanta United FC', 'Independiente',
       'Club AtlÃƒÂ©tico LanÃƒÂºs', 'RSC Anderlecht',
       'Ã„Â°stanbul BaÃ…Å¸akÃ…Å¸ehir FK', 'Hannover 96', 'Newcastle United',
       'MÃƒÂ¡laga CF', 'Trabzonspor', 'PSV', 'FC Augsburg', 'Club Tijuana',
       'VfB Stuttgart', 'Hamburger SV', 'CD LeganÃƒÂ©s', 'Getafe CF',
       'Deportivo AlavÃƒÂ©s', 'Portland Timbers', 'Kayserispor', 'Udinese',
       'Standard de LiÃƒÂ¨ge', 'Alanyaspor', '1. FSV Mainz 05',
       'Sparta Praha', 'FC Nantes', 'Al Ahli', 'SC Braga',
       'Brighton & Hove Albion', 'Levante UD', 'Boca Juniors',
       'Columbus Crew SC', 'QuerÃƒÂ©taro', 'Dijon FCO', 'Olympiakos CFP',
       'KRC Genk', 'FC Basel', 'Club AmÃƒÂ©rica', 'Montpellier HÃƒÂ©rault SC',
       'Monterrey', 'Seattle Sounders FC', 'River Plate',
       'CPD Junior Barranquilla', 'Racing Club de Avellaneda',
       'En Avant de Guingamp', 'Rangers', 'Colorado Rapids', 'Necaxa',
       'Aston Villa', 'KV Oostende', 'Akhisar Belediyespor',
       'Rubin Kazan', 'Rosario Central', 'Ferrara (SPAL)',
       'Wolverhampton Wanderers', 'Stade Rennais FC', 'Pachuca',
       'Granada CF', 'Colo-Colo', 'KAA Gent', 'Middlesbrough',
       'Toulouse FC', 'BSC Young Boys', 'FC St. Gallen',
       'Santos Futebol Clube', 'Cagliari', 'Rio Ave FC', 'Norwich City',
       'GrÃƒÂªmio Foot-Ball Porto Alegrense', 'Estudiantes de La Plata',
       'Cruzeiro', 'Universidad de Chile', 'Atletico Nacional Medellin',
       'FC Ufa', 'Girona CF', 'SM Caen', 'Independiente MedellÃƒ\xadn',
       'DjurgÃƒÂ¥rdens IF', 'VitÃƒÂ³ria GuimarÃƒÂ£es',
       'SÃƒÂ£o Paulo Futebol Clube', 'Royal Antwerp FC', 'Kaizer Chiefs',
       'Fulham', 'Sunderland', 'Huddersfield Town', 'PAOK Thessaloniki',
       'Fluminense Football Club', 'Leeds United', 'Derby County',
       'AC Ajaccio', 'Club LeÃƒÂ³n', 'Sociedade Esportiva Palmeiras',
       'Hellas Verona', 'Rayo Vallecano', 'Club Brugge KV',
       'Real Sporting de GijÃƒÂ³n', 'Celtic', 'Hull City',
       'Universidad CatÃƒÂ³lica', "CD O'Higgins", 'Club Atlas',
       'SC Freiburg', 'Melbourne City', 'Grupo Desportivo de Chaves',
       'Al Hilal', 'CA Osasuna', 'Perth Glory', 'Panathinaikos FC',
       'FC Utrecht', 'Club AtlÃƒÂ©tico HuracÃƒÂ¡n', 'Birmingham City',
       'Botafogo de Futebol e Regatas', 'Deportivo Toluca',
       'Amiens SC Football', 'Clube AtlÃƒÂ©tico Paranaense', 'GÃƒÂ¶ztepe',
       'FC Groningen', 'FC Ingolstadt 04', 'New England Revolution',
       'FC Red Bull Salzburg', 'Clube AtlÃƒÂ©tico Mineiro', 'Crotone',
       'Banfield', 'Grasshopper Club ZÃƒÂ¼rich', 'Vitesse', 'AZ Alkmaar',
       'SV Darmstadt 98', 'AvaÃƒ\xad Futebol Clube',
       'Coritiba Foot Ball Club', 'Legia Warszawa', 'RC Strasbourg',
       'Brescia', 'Vancouver Whitecaps FC', 'Western Sydney Wanderers',
       'Guadalajara', 'Cerezo Osaka', 'CS MarÃƒ\xadtimo', 'OsmanlÃ„Â±spor',
       'Santos Laguna', 'Dinamo Moscow', 'Monarcas Morelia', 'Frosinone',
       'Cruz Azul', 'Real Zaragoza', 'Deportes Iquique', 'Sydney FC',
       'Brisbane Roar', 'AEK Athens', 'Colon de Santa Fe',
       'Atiker Konyaspor', 'UniÃƒÂ³n EspaÃƒÂ±ola', 'Reading',
       'Asociacion Deportivo Cali', 'Palermo', 'FC Metz',
       'Sporting Kansas City', 'FC Seoul', 'Bursaspor',
       'Benevento Calcio', 'FC Rostov',
       'AssociaÃƒÂ§ÃƒÂ£o AtlÃƒÂ©tica Ponte Preta', 'Al Nassr',
       'San Jose Earthquakes', 'NÃƒÂ®mes Olympique', 'Al Ittihad',
       'Godoy Cruz', 'GimnÃƒ\xa0stic de Tarragona', 'Philadelphia Union',
       'Sport Club do Recife', 'CD Universidad de ConcepciÃƒÂ³n',
       'FC PaÃƒÂ§os de Ferreira', 'New York Red Bulls',
       'Club AtlÃƒÂ©tico Tigre', 'FC Lorient', 'Belgrano de CÃƒÂ³rdoba',
       'Sheffield Wednesday', 'CD Tenerife', 'SC Heerenveen',
       'Independiente Santa Fe', 'Puebla', 'VitÃƒÂ³ria SetÃƒÂºbal',
       'FC KÃƒÂ¸benhavn', 'Kalmar FF', 'CD Aves', "Newell's Old Boys",
       'Terek Grozny', '1. FC Union Berlin', 'Real Valladolid',
       'ADO Den Haag', 'Santiago Wanderers', 'Bari',
       'Ulsan Hyundai Horang-i', '1. FC Heidenheim', 'Argentinos Juniors',
       'Brentford', 'GenÃƒÂ§lerbirliÃ„Å¸i SK', 'FC St. Pauli',
       'Melbourne Victory', 'VfL Bochum', 'CÃƒÂ³rdoba CF',
       'AtlÃƒÂ©tico Clube Goianiense', 'Kardemir KarabÃƒÂ¼kspor',
       'AJ Auxerre', 'Real Oviedo', 'VitÃƒÂ³ria ', 'Arsenal Tula',
       'RC Lens', 'CF Os Belenenses', 'SK Rapid Wien',
       'Everton de ViÃƒÂ±a del Mar', 'CD Los Millionarios Bogota',
       'GwangJu FC', 'Sangju Sangmu FC', 'Jeonbuk Hyundai Motors',
       'FC Dallas', 'ES Troyes AC', 'F.B.C. Unione Venezia',
       'Al Qadisiyah', 'Fortuna DÃƒÂ¼sseldorf', 'Boavista FC',
       'D.C. United', 'Medicana Sivasspor', 'CD Once Caldas Manizales',
       'FC Ural', 'Kashiwa Reysol', 'MalmÃƒÂ¶ FF', 'CÃƒÂ¡diz C.F.',
       'Portimonense SC', 'Urawa Red Diamonds', 'UD AlmerÃƒ\xada',
       'AIK Solna', 'CD Huachipato', 'Estoril Praia', '1. FC NÃƒÂ¼rnberg',
       'Pescara', 'Stade de Reims', 'Moreirense FC', 'Empoli',
       'Orlando Pirates', 'FC Anzhi Makhachkala', 'Heracles Almelo',
       'Eintracht Braunschweig', 'Cremonese', 'CD Antofagasta',
       'AS Nancy Lorraine', 'Lobos de la BUAP', 'Suwon Samsung Bluewings',
       'Defensa y Justicia', 'Ipswich Town', 'Rosenborg BK', 'KAS Eupen',
       'FC Sion', 'Adelaide United', 'Real Salt Lake', 'FC Midtjylland',
       'Minnesota Thunder', 'AD AlcorcÃƒÂ³n', 'Al Faisaly', 'FC Tosno',
       'FC Twente', 'F.C. Tokyo', 'IF Elfsborg', 'Carpi', 'Parma',
       'IFK NorrkÃƒÂ¶ping', 'UniÃƒÂ³n de Santa Fe',
       'CorporaciÃƒÂ³n Club Deportivo TuluÃƒÂ¡', 'Kawasaki Frontale',
       'AssociaÃƒÂ§ÃƒÂ£o Chapecoense de Futebol', '1. FC Kaiserslautern',
       'Preston North End', 'Molde FK', 'Bristol City', 'BrÃƒÂ¸ndby IF',
       'Albacete BalompiÃƒÂ©', 'GFC Ajaccio', 'KV Kortrijk',
       'Kashima Antlers', 'CD Feirense', 'Oxford United',
       'Talleres de Cordoba', 'FC Lugano', 'SV Zulte-Waregem',
       'Deportes Tolima', 'Amkar Perm', 'KasimpaÃ…Å¸a SK',
       'Gimnasia y Esgrima La Plata', 'Queens Park Rangers',
       'Shimizu S-Pulse', 'Aalborg BK', 'Ãƒ\x81guilas Doradas',
       'FC Lausanne-Sports', 'Tiburones Rojos de Veracruz', 'Perugia',
       'La Spezia', 'Pohang Steelers', 'FC Barcelona B',
       'Evkur Yeni Malatyaspor', 'Willem II', 'Novara',
       'Sporting Charleroi', 'FK Austria Wien', 'Gamba Osaka',
       'DSC Arminia Bielefeld', 'Nottingham Forest', 'Salernitana',
       'Vercelli', 'Ã…Å¡lÃ„â€¦sk WrocÃ…â€šaw', 'Sagan Tosu', 'CD Numancia',
       'StrÃƒÂ¸msgodset IF', 'Yokohama F. Marinos', 'Cardiff City',
       'FC Sochaux-MontbÃƒÂ©liard', 'Jeju United FC', 'Lechia GdaÃ…â€žsk',
       'Piast Gliwice', 'SD Huesca', 'FC ZÃƒÂ¼rich', 'Heart of Midlothian',
       'AtlÃƒÂ©tico TucumÃƒÂ¡n', 'BK HÃƒÂ¤cken', 'Audax Italiano',
       'Club de Deportes Temuco', 'San Luis de Quillota', 'Al Taawoun',
       'Lech PoznaÃ…â€ž', 'FC Luzern', 'Cesena', 'Chacarita Juniors',
       'Aberdeen', 'Excelsior', 'SpVgg Greuther FÃƒÂ¼rth',
       'San MartÃƒ\xadn de San Juan', 'WisÃ…â€ša KrakÃƒÂ³w', 'Hammarby IF',
       'Virtus Entella', 'Vegalta Sendai', 'Alianza Petrolera',
       'CD Palestino', 'KV Mechelen', 'Central Coast Mariners',
       'La Equidad', 'Avellino', 'Omiya Ardija', 'Cracovia',
       'CuricÃƒÂ³ Unido', 'CF Reus Deportiu', 'SK Brann',
       'C.D. Leonesa S.A.D.', 'US Quevilly-Rouen', 'Sporting Lokeren',
       'Houston Dynamo', 'Termalica Bruk-Bet Nieciecza', 'Tondela',
       'SV Sandhausen', 'Al Fayha', 'Jeonnam Dragons',
       'Sandefjord Fotball', 'PogoÃ…â€ž Szczecin', 'Ãƒâ€“stersunds FK',
       'Burton Albion', 'Al Raed', 'Jagiellonia BiaÃ…â€šystok',
       'BahÃƒ\xada Blanca', 'Ventforet Kofu', 'Stade Brestois 29',
       'CD Lugo', 'Korona Kielce', 'PEC Zwolle', 'MSV Duisburg',
       'AFC Eskilstuna', 'Waasland-Beveren', 'Club AtlÃƒÂ©tico Patronato',
       'La Berrichonne de ChÃƒÂ¢teauroux', 'SK Sturm Graz',
       'Royal Excel Mouscron', 'JÃƒÂºbilo Iwata', 'SÃƒÂ¸nderjyskE',
       'Al Shabab', 'US OrlÃƒÂ©ans Loiret Football',
       'Bourg en Bresse PÃƒÂ©ronnas 01', 'FC NordsjÃƒÂ¦lland', 'FC Thun',
       'CD America de Cali', 'VVV-Venlo', 'Charlton Athletic',
       'Sevilla AtlÃƒÂ©tico', 'Ternana', 'Gangwon FC', 'IFK GÃƒÂ¶teborg',
       'Odense Boldklub', 'Arsenal de SarandÃƒ\xad', 'SG Dynamo Dresden',
       'Bolton Wanderers', 'Plymouth Argyle', 'Southend United',
       'VÃƒÂ©lez Sarsfield', 'Daegu FC', 'Sanfrecce Hiroshima', 'Odds BK',
       'Aarhus GF', 'Blackburn Rovers', 'Lyngby BK', 'FC Erzgebirge Aue',
       'Sint-Truidense VV', 'Karlsruher SC', 'Jaguares FÃƒÂºtbol Club',
       'Sarpsborg 08 FF', 'Temperley', ' SSV Jahn Regensburg',
       'Patriotas BoyacÃƒÂ¡ FC', 'Barnsley', 'Sandecja Nowy SÃ„â€¦cz',
       'GÃƒÂ³rnik Zabrze', 'VfL OsnabrÃƒÂ¼ck', 'Valenciennes FC', 'Tours FC',
       'Lorca Deportiva CF', 'Albirex Niigata', 'Cittadella',
       'Aalesunds FK', 'Deportivo Pasto', 'Roda JC Kerkrade',
       'Motherwell', 'Holstein Kiel', 'Scunthorpe United',
       'AtlÃƒÂ©tico Huila', 'WisÃ…â€ša PÃ…â€šock', 'AtlÃƒÂ©tico Bucaramanga',
       'Sparta Rotterdam', 'StabÃƒÂ¦k Fotball', 'WÃƒÂ¼rzburger FV',
       'VfR Aalen', 'Clermont Foot 63', 'Randers FC',
       'VÃƒÂ¥lerenga Fotball', 'Incheon United FC', 'Hibernian',
       'SCR Altach', 'Sheffield United', 'Le Havre AC', 'Walsall',
       'Chamois Niortais FC', 'Sportfreunde Lotte', 'Millwall',
       'SpVgg Unterhaching', 'FC SKA-Energiya Khabarovsk',
       'Hansa Rostock', 'Wellington Phoenix', 'Hobro IK',
       'Wigan Athletic', 'Peterborough United', 'Chemnitzer FC',
       'Grimsby Town', 'Ascoli', 'Al Fateh', 'Foggia', 'Bristol Rovers',
       '1. FC Magdeburg', 'SG Sonnenhof GroÃƒÅ¸aspach', 'Bury',
       'LillestrÃƒÂ¸m SK', 'Arka Gdynia', 'Ross County FC', 'Paris FC',
       'Bradford City', 'Hamilton Academical FC', 'Luton Town',
       'NAC Breda', 'Portsmouth', 'ZagÃ…â€šÃ„â„¢bie Lubin', 'Kilmarnock',
       'Hokkaido Consadole Sapporo', 'Ãƒâ€“rebro SK', 'SV Wehen Wiesbaden',
       'Coventry City', 'Milton Keynes Dons', 'Rochdale', 'FK Haugesund',
       'Dundee FC', 'Oldham Athletic', 'Ohod Club', 'Rotherham United',
       'HJK Helsinki', 'LASK Linz', 'AC Horsens', 'SC Fortuna KÃƒÂ¶ln',
       'St. Johnstone FC', 'Sogndal', 'Envigado FC', 'Blackpool',
       'SC PreuÃƒÅ¸en MÃƒÂ¼nster', 'Hallescher FC', 'Ettifaq FC',
       'Crawley Town', 'Exeter City', 'AFC Wimbledon', 'Doncaster Rovers',
       'IK Sirius', 'JÃƒÂ¶nkÃƒÂ¶pings SÃƒÂ¶dra IF', 'Rot-WeiÃƒÅ¸ Erfurt',
       'Notts County', 'SV Mattersburg', 'Viking FK', 'Cambridge United',
       'Tigres FC', 'Mansfield Town', 'SV Meppen', 'TromsÃƒÂ¸ IL',
       'Swindon Town', 'Werder Bremen II', 'FC Admira Wacker MÃƒÂ¶dling',
       'SC Paderborn 07', 'Partick Thistle F.C.', 'Silkeborg IF',
       'Al Batin', 'Colchester United', 'FSV Zwickau', 'Crewe Alexandra',
       'Northampton Town', 'Kristiansund BK', 'Lincoln City', 'Dundalk',
       'Wycombe Wanderers', 'Yeovil Town', 'GIF Sundsvall',
       'FC Carl Zeiss Jena', "St. Patrick's Athletic", 'Fleetwood Town',
       'Wolfsberger AC', 'Cork City', 'Gillingham', 'SKN St. PÃƒÂ¶lten',
       'Carlisle United', 'Chesterfield', 'Newcastle Jets', 'Morecambe',
       'Port Vale', 'Newport County', 'Shrewsbury', 'Accrington Stanley',
       'Forest Green', 'Bohemian FC', 'Cheltenham Town', 'Barnet',
       'Halmstads BK', 'Shamrock Rovers', 'Derry City', 'Stevenage',
       'Finn Harps', 'FC HelsingÃƒÂ¸r', 'Sligo Rovers', 'Bray Wanderers',
       'Limerick FC', 'Galway United', 'Drogheda United'], dtype=object)

# Reduce dimension by combining position types and stats

In [57]:
positiontype_to_cols = {
    'Attack': ['LS', 'ST', 'RS', 'LF', 'CF', 'RF'],
    'Midfield': ['LW', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'CDM', 'RDM', 'LDM'],
    'Defense': ['LWB', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB']
}

for pos_type, colvec in positiontype_to_cols.items():
    df[pos_type + '_rate'] = round(df[colvec].mean(axis=1))
    
summaryname_to_cols = {
    'Passing': ['Crossing', 'Short passing', 'Long passing'],
    'Shooting': ['Finishing', 'Volleys', 'Free kick accuracy', 'Shot power',
                 'Long shots', 'Penalties', 'Heading accuracy'],
    'Defending': ['Marking', 'Standing tackle', 'Sliding tackle', 'Interceptions'],
    'Speed': ['Sprint speed', 'Agility', 'Acceleration', 'Reactions', 'Stamina'],
    'Control': ['Ball control', 'Curve', 'Dribbling'],
    'GoalKeeping': ['GK diving', 'GK handling', 'GK positioning', 'GK kicking', 'GK reflexes'],
    'Mental': ['Composure', 'Vision', 'Aggression', 'Positioning'],
    'Power': ['Strength', 'Balance', 'Jumping'],
    'Avg_rating': ['Overall', 'Potential']
    
}

for summarycol, colvec in summaryname_to_cols.items():
    df[summarycol] = round(df[colvec].mean(axis=1))

In [58]:
df.head()

,Unnamed: 0,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Defense_rate,Passing,Shooting,Defending,Speed,Control,GoalKeeping,Mental,Power,Avg_rating
0,0,Cristiano Ronaldo,32,https://cdn.sofifa.org/48/18/players/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,...,59.00,nan,nan,nan,nan,nan,nan,nan,nan,94.00
1,1,L. Messi,30,https://cdn.sofifa.org/48/18/players/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,93,93,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,...,53.00,nan,nan,nan,nan,nan,nan,nan,nan,93.00
2,2,Neymar,25,https://cdn.sofifa.org/48/18/players/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,94,Paris Saint-Germain,https://cdn.sofifa.org/24/18/teams/73.png,...,55.00,nan,nan,nan,nan,nan,nan,nan,nan,93.00
3,3,L. SuÃƒÂ¡rez,30,https://cdn.sofifa.org/48/18/players/176580.png,Uruguay,https://cdn.sofifa.org/flags/60.png,92,92,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,...,63.00,nan,nan,nan,nan,nan,nan,nan,nan,92.00
4,4,M. Neuer,31,https://cdn.sofifa.org/48/18/players/167495.png,Germany,https://cdn.sofifa.org/flags/21.png,92,92,FC Bayern Munich,https://cdn.sofifa.org/24/18/teams/21.png,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,92.00

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 87 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17981 non-null  int64
 1   Name                 17981 non-null  object
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  object
 4   Nationality          17981 non-null  object
 5   Flag                 17981 non-null  object
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  object
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  int32
 11  Wage                 17981 non-null  int32
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  object
 14  Aggression           17981 non-null  object
 15  Agility              17981 non-null  object
 16  Balance              17981 non-null  object
 17  Ball control         17981 non-null  object
 18  Composure            17981 non-null  object
 19  Crossing             17981 non-null  object
 20  Curve                17981 non-null  object
 21  Dribbling            17981 non-null  object
 22  Finishing            17981 non-null  object
 23  Free kick accuracy   17981 non-null  object
 24  GK diving            17981 non-null  object
 25  GK handling          17981 non-null  object
 26  GK kicking           17981 non-null  object
 27  GK positioning       17981 non-null  object
 28  GK reflexes          17981 non-null  object
 29  Heading accuracy     17981 non-null  object
 30  Interceptions        17981 non-null  object
 31  Jumping              17981 non-null  object
 32  Long passing         17981 non-null  object
 33  Long shots           17981 non-null  object
 34  Marking              17981 non-null  object
 35  Penalties            17981 non-null  object
 36  Positioning          17981 non-null  object
 37  Reactions            17981 non-null  object
 38  Short passing        17981 non-null  object
 39  Shot power           17981 non-null  object
 40  Sliding tackle       17981 non-null  object
 41  Sprint speed         17981 non-null  object
 42  Stamina              17981 non-null  object
 43  Standing tackle      17981 non-null  object
 44  Strength             17981 non-null  object
 45  Vision               17981 non-null  object
 46  Volleys              17981 non-null  object
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  LAM                  15952 non-null  float64
 53  LB                   15952 non-null  float64
 54  LCB                  15952 non-null  float64
 55  LCM                  15952 non-null  float64
 56  LDM                  15952 non-null  float64
 57  LF                   15952 non-null  float64
 58  LM                   15952 non-null  float64
 59  LS                   15952 non-null  float64
 60  LW                   15952 non-null  float64
 61  LWB                  15952 non-null  float64
 62  Preferred Positions  17981 non-null  object
 63  RAM                  15952 non-null  float64
 64  RB                   15952 non-null  float64
 65  RCB                  15952 non-null  float64
 66  RCM                  15952 non-null  float64
 67  RDM                  15952 non-null  float64
 68  RF                   15952 non-null  float64
 69  RM                   15952 non-null  float64
 70  RS                   15952 non-null  float64
 71  RW                   15952 non-null  float64
 72  RWB                  15952 non-null  float64
 73  ST                   15952 non-null  float64
 74  Position             17981 non-null  object
 75  Attack_rate          15952 non-null  float64
 76  Midfield_rate        15952 non-null  float64
 77  Defense_rate         15952 non-null  float64
 78  Passing              0 non-null      float64
 79  Shooting             0 non-null      float64
 80  Defending            0 non-null      float64
 81  Speed                0 non-null      float64
 82  Control              0 non-null      float64
 83  GoalKeeping          0 non-null      float64
 84  Mental               0 non-null      float64
 85  Power                0 non-null      float64
 86  Avg_rating           17981 non-null  float64
dtypes: float64(38), int32(2), int64(5), object(42)
memory usage: 11.8+ MB